Part 1: The first model we use is Naive bayes model and the accuracy is 0.157.

In [177]:
import pandas as pd
import numpy as np

In [178]:
train_features = pd.read_csv(open("train_features.tsv"),sep = '\t')

In [179]:
train_features

,movieId,title,YTId,year,tag,avf1,avf2,avf3,avf4,avf5,...,ivec11,ivec12,ivec13,ivec14,ivec15,ivec16,ivec17,ivec18,ivec19,ivec20
0,89,Nick of Time,PaLHJCnAXi4,1995,"johnny_depp,suspense",0.322418,0.556350,0.242215,0.495954,0.208952,...,0.356415,-0.110838,0.166033,0.024820,-0.002862,-0.148170,0.107387,0.132345,-0.201218,-0.110445
1,93,Vampire in Brooklyn,dNwt2Demll8,1995,"vampires,clv",0.405104,0.326187,0.161139,0.220981,0.138873,...,0.027518,-0.110933,0.121582,0.034794,0.064049,-0.052943,0.049259,0.226385,-0.176054,0.075328
2,94,Beautiful Girls,yfQ5ONwWxI8,1996,"beautiful,natalie_portman,humorous,violence,at...",0.174210,0.244351,0.224792,0.182745,0.182964,...,0.074289,-0.049883,-0.043058,-0.021249,0.130764,-0.003852,0.108196,0.165733,0.001866,0.148428
3,95,Broken Arrow,De29KipeZQw,1996,"action,military,r,clv",0.306253,0.404918,0.207036,0.295412,0.175561,...,0.337192,-0.265329,-0.032534,0.101191,0.027917,0.264389,0.063412,0.393824,0.388000,-0.135409
4,97,"Hate Haine, La)",cy5TaO6qTBU,1995,"black_and_white,disturbing,drugs,social_commen...",0.276518,0.153422,0.178382,0.148427,0.173064,...,0.568660,-0.176512,0.180269,-0.057015,0.006506,-0.094857,0.192810,0.107635,-0.163594,0.304205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5235,129857,Bright Days Ahead,Wzx0oRXvVws,2013,romance,0.205904,0.260723,0.454154,0.242067,0.398921,...,-0.037794,-0.033184,-0.060990,0.082438,0.239687,-0.129511,0.049127,0.051957,0.293846,-0.295924
5236,129913,Rings,NbHRP43ocWQ,2005,horror,0.365200,0.301348,0.220274,0.230023,0.196659,...,0.158865,0.074359,-0.130092,0.161759,-0.000771,0.083852,-0.041330,0.146908,0.107092,-0.164037
5237,130444,Ruby Red,bhXxVJmvCuQ,2013,time_travel,0.204054,0.440529,0.249341,0.380168,0.161565,...,-0.097081,0.022597,-0.050303,0.011482,-0.120616,-0.175078,-0.198621,0.078244,0.073724,-0.050687
5238,130490,Insurgent,IR-l_TSjlEo,2015,"action,stupid,based_on_a_book",0.366651,0.263861,0.195416,0.186381,0.162039,...,0.036049,0.205347,-0.129891,-0.110448,0.179365,0.049375,-0.082367,0.186267,-0.082937,0.031778
5239,130626,Vengeance Can Wait,WmthskXrOLs,2010,quirky,0.425849,0.154565,0.195336,0.136701,0.177798,...,0.146592,-0.120706,-0.143269,0.129943,0.115335,0.122248,-0.033699,0.029952,-0.175468,-0.210260

In [180]:
train_labels = pd.read_csv(open("train_labels.tsv"),sep = '\t')

In [181]:
train_labels

      movieId    genres
0          89  Thriller
1          93   Romance
2          94   Romance
3          95  Thriller
4          97     Crime
...       ...       ...
5235   129857   Romance
5236   129913  Thriller
5237   130444   Fantasy
5238   130490   Romance
5239   130626   Romance

[5240 rows x 2 columns]

In [182]:
y = np.array(train_lables['genres'])

In [183]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_features['tag'] = le.fit_transform(train_features['tag'])
X = np.array(train_features.drop(columns=['title', 'YTId']))

In [184]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,y)
GaussianNB()

GaussianNB(priors=None, var_smoothing=1e-09)

In [185]:
test_features = pd.read_csv(open("valid_features.tsv"),sep = '\t')
test_labels = pd.read_csv(open("valid_labels.tsv"),sep = '\t')

test_features['tag'] = le.fit_transform(test_features['tag'])
X_test = np.array(test_features.drop(columns=['title', 'YTId']))

y_test = np.array(test_labels['genres'])

In [186]:
accuracy = clf.score(X_test, y_test)
print(accuracy)

0.15719063545150502

Part 2: Several other models are used in this part and compared by their accuracy

In [187]:
train_features_2 = pd.read_csv(open("train_features.tsv"),sep = '\t')
train_labels_2 = pd.read_csv(open("train_labels.tsv"),sep = '\t')

X_2 = train_features_2.drop(columns=['YTId','movieId'])
X_2

,title,year,tag,avf1,avf2,avf3,avf4,avf5,avf6,avf7,...,ivec11,ivec12,ivec13,ivec14,ivec15,ivec16,ivec17,ivec18,ivec19,ivec20
0,Nick of Time,1995,"johnny_depp,suspense",0.322418,0.556350,0.242215,0.495954,0.208952,0.558998,55.2631,...,0.356415,-0.110838,0.166033,0.024820,-0.002862,-0.148170,0.107387,0.132345,-0.201218,-0.110445
1,Vampire in Brooklyn,1995,"vampires,clv",0.405104,0.326187,0.161139,0.220981,0.138873,0.751276,62.8028,...,0.027518,-0.110933,0.121582,0.034794,0.064049,-0.052943,0.049259,0.226385,-0.176054,0.075328
2,Beautiful Girls,1996,"beautiful,natalie_portman,humorous,violence,at...",0.174210,0.244351,0.224792,0.182745,0.182964,0.593009,54.2002,...,0.074289,-0.049883,-0.043058,-0.021249,0.130764,-0.003852,0.108196,0.165733,0.001866,0.148428
3,Broken Arrow,1996,"action,military,r,clv",0.306253,0.404918,0.207036,0.295412,0.175561,0.663003,58.3163,...,0.337192,-0.265329,-0.032534,0.101191,0.027917,0.264389,0.063412,0.393824,0.388000,-0.135409
4,"Hate Haine, La)",1995,"black_and_white,disturbing,drugs,social_commen...",0.276518,0.153422,0.178382,0.148427,0.173064,0.670609,62.7541,...,0.568660,-0.176512,0.180269,-0.057015,0.006506,-0.094857,0.192810,0.107635,-0.163594,0.304205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5235,Bright Days Ahead,2013,romance,0.205904,0.260723,0.454154,0.242067,0.398921,0.340725,49.3000,...,-0.037794,-0.033184,-0.060990,0.082438,0.239687,-0.129511,0.049127,0.051957,0.293846,-0.295924
5236,Rings,2005,horror,0.365200,0.301348,0.220274,0.230023,0.196659,0.591406,57.8990,...,0.158865,0.074359,-0.130092,0.161759,-0.000771,0.083852,-0.041330,0.146908,0.107092,-0.164037
5237,Ruby Red,2013,time_travel,0.204054,0.440529,0.249341,0.380168,0.161565,0.670678,58.8675,...,-0.097081,0.022597,-0.050303,0.011482,-0.120616,-0.175078,-0.198621,0.078244,0.073724,-0.050687
5238,Insurgent,2015,"action,stupid,based_on_a_book",0.366651,0.263861,0.195416,0.186381,0.162039,0.653945,57.0884,...,0.036049,0.205347,-0.129891,-0.110448,0.179365,0.049375,-0.082367,0.186267,-0.082937,0.031778
5239,Vengeance Can Wait,2010,quirky,0.425849,0.154565,0.195336,0.136701,0.177798,0.649929,59.6584,...,0.146592,-0.120706,-0.143269,0.129943,0.115335,0.122248,-0.033699,0.029952,-0.175468,-0.210260

In [188]:
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import OneHotEncoder
column_trans = ColumnTransformer(
     [('tag_category', CountVectorizer(),'tag'),
      ('title_bow', CountVectorizer(), 'title')],
     remainder='passthrough')


X_2_clean = column_trans.fit_transform(X_2)
y_2_clean = np.array(train_labels_2['genres'])

In [189]:
test_features_2 = pd.read_csv(open("valid_features.tsv"),sep = '\t')
test_labels_2 = pd.read_csv(open("valid_labels.tsv"),sep = '\t')

X_test_2 = test_features_2.drop(columns=['YTId','movieId'])
X_test_2_clean = column_trans.transform(X_test_2)
y_test_2_clean = np.array(test_labels_2['genres'])

In [190]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn import tree
from sklearn.linear_model import LogisticRegression
models = [
    ('SVM', SVC()),
    ('KNN', KNeighborsClassifier()),
    ('AB', AdaBoostClassifier()),
    ('RF', RandomForestClassifier()),
    ('DT', tree.DecisionTreeClassifier()),
    ('LR', LogisticRegression(random_state=0)),
    
]

In [191]:
for name, model in models:
    clf = model
    clf.fit(X_2_clean, y_2_clean)
    accuracy = clf.score(X_test_2_clean, y_test_2_clean)
    print(name, accuracy)

/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVM 0.20735785953177258
KNN 0.1605351170568562
AB 0.22408026755852842

/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

RF 0.2040133779264214
DT 0.22073578595317725

/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LR 0.4080267558528428

/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

part 3: This is the code of using logistic regression model to predict the test features.

In [206]:
score_features = pd.read_csv(open("NEW_test_features.tsv"),sep = '\t')
df = score_features[['movieId']]
X_3 = score_features.drop(columns=['YTId','movieId'])
X_3_clean = column_trans.transform(X_3)
df

     movieId
0      91511
1      91535
2      91542
3      91797
4      91826
..       ...
230   121342
231   125918
232   126591
233   127993
234   128671

[235 rows x 1 columns]

In [215]:
LR = LogisticRegression(random_state=0)
LR.fit(X_2_clean, y_2_clean)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [216]:
result = LR.predict(X_3_clean)

In [217]:
df['genres'] = pd.Series(result, index=df.index)
df

/Users/tianqilyu/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

     movieId   genres
0      91511  Romance
1      91535   Horror
2      91542  Mystery
3      91797    Drama
4      91826    Drama
..       ...      ...
230   121342  Romance
231   125918   Comedy
232   126591  Fantasy
233   127993  Fantasy
234   128671    Drama

[235 rows x 2 columns]

In [210]:
df.to_csv(r'result.csv', index = False)